### PR TITLE
npm package

### PR DESCRIPTION
**Pull request by gtanner**
Hello,

I created a quick npm(http://npmjs.org/) package for this project to help those of us using it in node projects.

I changed the exports signature to be a little more natural for development with require, so the signature went from:

```
var jsDump = require("jsDump").jsDump;
```

to

```
var jsDump = require("jsDump"):
```

I didn't upload this to the npm repository since I figured you would probably want to control the releases.

Cheers,

Gord

### CODE REVIEW

**Comment by NV** [comment]
Thanks, merged!

**Comment by NV** [comment]
Could you tell me how do you use jsDump? These days Node already comes with nice `utils.inspect` that used in REPL.

**Comment by gtanner** [comment]
I created a node server that allows remote REPL commands to be run on browsers (will be open sourced soon)

So I wanted something taht I could use on the server as well as the browser client

**Comment by NV** [comment]
I used to build [node-web-repl](https://github.com/nko/node-web-repl) using [node's repl module](https://github.com/joyent/node/blob/master/lib/repl.js).

**Pull request merged**
